---
booktitle: Proceedings of the 2017 Conference on Learning Theory
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
shortname: COLT
volume: 65
year: '2017'
start: 2017-07-07
end: 2017-07-10
url: https://proceedings.mlr.press
author:
  name: PMLR
location: Amsterdam, Netherlands
published: 2017-06-18
layout: proceedings
publisher: PMLR
series: Proceedings of Machine Learning Research
issn: 2640-3498
id: COLT-2017
month: 0
cycles: false
editor:
- given: Satyen
  family: Kale
- given: Ohad
  family: Shamir
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the 2017 Conference on Learning Theory on 07-10 July 2017

  Published as Volume 65 by the Proceedings of Machine Learning Research on 18 June 2017.

  Volume Edited by:
    Satyen Kale
    Ohad Shamir

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 07--10 Jul
baseurl: "/v65"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
style: pmlr
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
permalink: "/:title.html"
ghub:
  edit: true
  repository: v65
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
email: ''
conference:
  name: Conference on Learning Theory
  url: http://www.learningtheory.org/colt2017/
  location: Amsterdam, Netherlands
  dates:
  - 2017-07-07
  - 2017-07-08
  - 2017-07-09
  - 2017-07-10
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
